### PR TITLE
Handle scaling of markdown images

### LINKED ISSUE #83: Handle scaling of images that are added via markdown
## Describe the bug
Images that is added directly in markdown-content of a file is not scaling well. 

## Steps to reproduce
Have a look at the image on the page /about and make the window size smaller. 

## Expected behavior
- [ ] Make sure the image scales according to the screen size.

### PR DESCRIPTION
**Pull request by AnnikaSonnek**
## Related issue(s) and PR(s)
This PR closes https://github.com/NBISweden/bacmet/issues/83

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## List of changes made
- Scale images added with markdown
- Fix issue with hamburger menu in mobile version of website

## Screenshot of the fix
image

image

## Testing
Check out this branch and check that the image on the About-page scales when the screen becomes smaller. Also check the hamburger menu when the screen is smaller. 

## Further comments
I have only made the image scale with CSS. This is because the content is supposed to be dynamic and I think that it would be a bit more complicated asking the content creators to upload three different sizes of the same image and incorporating that with `react-markdown`. Instead, for this target group, it would be easier that they upload one image size instead and that they make sure that image is a reasonable size. 

But if anyone is interested in deep diving into how this would be done, feel free! I however felt that it was out of scope for this particular issue. 

## Definition of Done checklist
- [x] I have made an effort making the commit history understandable
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [ ] Existing tests are passing and I wrote unit tests for new functionality
- [x] My changes generate no new warnings
- [x] Make sure the layout and text follow design sketches, if there are any

### CODE REVIEW

**Review by pdmnyberg — APPROVED** [review]
This looks reasonable and works great. Good work.

File: frontend/bacmet/app/about/page.tsx [hunk 1]
```diff
@@ -11,7 +11,18 @@ export default function About() {
 
   return (
     <div className="text-center pt-3">
-      <ReactMarkdown>{content}</ReactMarkdown>
+      <ReactMarkdown
+        components={{
+          img: ({ node, ...props }) => (
+            <img
```
Comment (pdmnyberg) [inline frontend/bacmet/app/about/page.tsx]: Taking another lap. I think that this change should be applied generally for all markdown pages. We should make this a utility component that is reused.

**Review by pdmnyberg — CHANGES_REQUESTED** [review]
I changed my mind slightly. Please try to make you solution reusable. Possibly also apply it on the other pages using markdown.

File: frontend/bacmet/app/about/page.tsx (hunk 1 above)
Comment (AnnikaSonnek) [reply frontend/bacmet/app/about/page.tsx]: Ah yes, I understand what you mean! I will look into it!

**Review by pdmnyberg — APPROVED** [review]
LGTM
